// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $Game from "./islands/Game.tsx";
import * as $ReversiBoard from "./islands/ReversiBoard.tsx";
import * as $StartScreen from "./islands/StartScreen.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Game.tsx": $Game,
    "./islands/ReversiBoard.tsx": $ReversiBoard,
    "./islands/StartScreen.tsx": $StartScreen,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
